---
spring:
  application:
    name: "hr"
  profiles:
    active: "smart"
  thymeleaf:
    cache: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/hr"
    username: "hradmin"
    password: "hradmin"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: "update"
    properties:
      hibernate:
        highlight_sql: true

salary:
  defaultPercent: 5
  smart:
    limits:
    - year: 10
      percent: 10
    - year: 5
      percent: 5
    - year: 2.5
      percent: 2